name: release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  windows:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: clear.7z
            asset_name: clear-windows-x86_64.7z

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.9.8'

      - name: Package
        run: |
          xmake config --yes --policies=package.cmake_generator.ninja --test=n --dev=n
          xmake
          xmake pack

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/xpack/clipboard-url-clear/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
